apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: user-registration
spec:
  template:
    metadata:
      name: user-registration-v2
    spec:
      containers:
        - image: quay.io/microcks/quarkus-user-registration:latest
          name: user-container
          ports:
            - containerPort: 8383
          env:
            - name: QUARKUS_PROFILE
              value: kube
